# These two properties are required
domain = "https://appen.atlassian.net"
user_email = "rmcclain@appen.com"
db_file = true # If true, it will create a cached db in the /tmp directory.  Which can live for 10 days.

[tickets]
# Show tickets assigned to you only.  Can include unassigned.
current_user_tickets_only = true
# Show tickets in these status only
show_ticket_status = ["In Progress"]

[projects]
default_projects = "ADAP" # Can be multiple per jira API -  For example, keys=PA&keys=PB. Up to 50 project keys can be provided.

