wtf:
  colors:
    background: "black"
    border:
      focusable: "darkslateblue"
      focused: "orange"
      normal: "gray"
    checked: "gray"
    highlight:
      fore: "red"
      back: "green"
    text: "white"
    title: "white"
  grid:
    # How _wide_ the columns are, in terminal characters. In this case we have
    # six columns, each of which are 35 characters wide
    columns: [80, 80, 80 ]

    # How _high_ the rows are, in terminal lines. In this case we have five rows
    # that support ten line of text, one of three lines, and one of four
    rows: [30, 30, 30]
  navigation:
    shortcuts: true
  openFileUtil: "open"
  sigils:
    checkbox:
      checked: "x"
      unchecked: " "
    paging:
      normal: "*"
      selected: "_"
  term: "xterm-256color"
  mods:
    github:
      apiKey: "c3d2f0ddd7955be6c383bb1be181b0053317137f"
      customQueries:
        othersPRs:
          title: "Others Pull Requests"
          filter: "is:open is:pr -author:rmcclaincf"
      enabled: true
      enableStatus: true
      repositories:
        - Crowdflower/Crowdflower
        - Crowdflower/f8-development-env-tools
        - Crowdflower/customer-data-service
        - Crowdflower/audit-service
        - Crowdflower/requestor-proxy
      position:
        top: 0
        left: 0
        height: 3
        width: 1
      refreshInterval: 300
      username: "rmcclaincf"
    jira:
      apiKey: "4nZCuq10aLvzPYYRb2ln20B0"
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      domain: "https://appen.atlassian.net"
      email: "ron.mcclain@figure-eight.com"
      enabled: true
      jql: "resolution = unresolved ORDER BY priority asc, created"
      position:
        top: 0
        left: 1 
        height: 3
        width: 1
      project: "_Client Workspace"
      refreshInterval: 900
      username: "ron.mcclain"
      #verifyServerCertificate: true
    bittrex:
      colors:
        base:
          name: orange
          displayName: red
        market:
          name: red
          field: white
          value: green
      enabled: true
      position:
        top: 0
        left: 2 
        height: 3
        width: 1
      refreshInterval: 5
      summary:
        USD:
          displayName: Bitcoin
          market:
          - BTC
          - LTC
          - ETH
