lastupdatecheck: 0
recentrepos:
- /Users/mixtli/dotfiles
- /Users/mixtli/Projects/go/rssagg
startuppopupversion: 5
lastversion: 0.41.0
customcommandshistory: []
hidecommandlog: false
ignorewhitespaceindiffview: false
diffcontextsize: 3
localbranchsortorder: recency
remotebranchsortorder: alphabetical
gitlogorder: topo-order
gitlogshowgraph: always
